### PR TITLE
Background messages

### PR DESCRIPTION
**Pull request by pedregalux**
with python 3.9 i got this error when migrate:

```
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given
```

i try:
  _XMLParser.__init__(self, target=target, encoding=encoding)

and migrate run ok

### CODE REVIEW

**Comment by brandonrobertz** [comment]
Can you explain more about the `_XMLParser.init(self, target=target, encoding=encoding)` error? Where did you make this change?

**Comment by pedregalux** [comment]
My apologies for the incomplete.  It is in: "django-collaborative / env / lib / python3.9 / site-packages / defusedxml / ElementTree.py", line 68

**Comment by pedregalux** [comment]
here i found the info: https://github.com/tiran/defusedxml/issues/29

**Comment by brandonrobertz** [comment]
I'm a little confused. Your PR is attempting to merge the `background-messages` branch into main (with no additional changes), but you're talking about something in the `defusedxml` library. What is your intent with this PR?

**Comment by pedregalux** [comment]
Sorry, i move it to issues.

**Pull request closed without merging**
